// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  image: dynamic(() => import('./Image')),
  text: dynamic(() => import('./Text')),
  text_grid: dynamic(() => import('./TextGrid')),
  text_image: dynamic(() => import('./TextImage')),
};
